ALTER TYPE "DriverStatus" ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE "DriverStatus" ADD VALUE IF NOT EXISTS 'REJECTED';

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "vehicleType" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "verificationStatus" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "verificationSubmittedAt" TIMESTAMP(3);

ALTER TABLE "User" ALTER COLUMN "driverStatus" SET DEFAULT 'PENDING';
UPDATE "User" SET "driverStatus" = 'PENDING' WHERE "driverStatus" IS NULL;
ALTER TABLE "User" ALTER COLUMN "driverStatus" SET NOT NULL;
