export type PlaceType =
  | "DEPARTMENT"
  | "COMMUNE"
  | "ARRONDISSEMENT"
  | "QUARTIER"
  | "VILLAGE"
  | "LANDMARK"
  | "MARKET"
  | "AREA";

export type BeninPlace = {
  id: string;
  name: string;
  normalizedName: string;
  type: PlaceType;
  department: string | null;
  commune: string | null;
  arrondissement: string | null;
  city: string | null;
  country: "Bénin";
  aliases: string[];
  latitude: number | null;
  longitude: number | null;
  priority: number;
  isServiceable: boolean;
};

/*
  Coordonnées approximatives (centres-villes / quartiers).
  Les lat/lon sont indicatives pour le calcul de distance.
  Source : approximations open-data / cartes publiques.
  Priorité : 10 = très haute (Cotonou/Calavi/Sème/Porto-Novo),
             7 = haute (grandes villes),
             5 = moyenne,
             3 = basse.
*/

export const BENIN_PLACES: BeninPlace[] = [
  // ===================== COTONOU (Littoral) =====================
  { id: "bj-cotonou", name: "Cotonou", normalizedName: "cotonou", type: "COMMUNE", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["ctn", "cotonou ville"], latitude: 6.3703, longitude: 2.3912, priority: 10, isServiceable: true },
  { id: "bj-cadjehoun", name: "Cadjèhoun", normalizedName: "cadjehoun", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["cadje", "cadjehoun centre"], latitude: 6.3535, longitude: 2.4305, priority: 10, isServiceable: true },
  { id: "bj-haievive", name: "Haie Vive", normalizedName: "haie vive", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["haie-vive", "haie vive cotonou"], latitude: 6.3645, longitude: 2.4270, priority: 10, isServiceable: true },
  { id: "bj-fidjrosse", name: "Fidjrossè", normalizedName: "fidjrosse", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["fidjrosse plage", "fidjrosse centre"], latitude: 6.3530, longitude: 2.3945, priority: 10, isServiceable: true },
  { id: "bj-akpakpa", name: "Akpakpa", normalizedName: "akpakpa", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["akpakpa cotonou"], latitude: 6.3580, longitude: 2.4420, priority: 10, isServiceable: true },
  { id: "bj-akpakpa-dodomey", name: "Akpakpa Dodomey", normalizedName: "akpakpa dodomey", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["dodomey"], latitude: 6.3650, longitude: 2.4500, priority: 10, isServiceable: true },
  { id: "bj-akpakpa-centre", name: "Akpakpa Centre", normalizedName: "akpakpa centre", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["akpakpa-centre"], latitude: 6.3600, longitude: 2.4400, priority: 10, isServiceable: true },
  { id: "bj-ganhi", name: "Ganhi", normalizedName: "ganhi", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["ganhi cotonou"], latitude: 6.3630, longitude: 2.4180, priority: 10, isServiceable: true },
  { id: "bj-tokpa", name: "Tokpa", normalizedName: "tokpa", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["tokpa cotonou"], latitude: 6.3660, longitude: 2.4250, priority: 10, isServiceable: true },
  { id: "bj-dantokpa", name: "Dantokpa", normalizedName: "dantokpa", type: "MARKET", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["marche dantokpa", "marché dantokpa", "dan tokpa"], latitude: 6.3680, longitude: 2.4200, priority: 10, isServiceable: true },
  { id: "bj-zongo", name: "Zongo", normalizedName: "zongo", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["zongo cotonou"], latitude: 6.3710, longitude: 2.4160, priority: 10, isServiceable: true },
  { id: "bj-gbegamey", name: "Gbégamèy", normalizedName: "gbegamey", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["gbegamey", "gbegame"], latitude: 6.3850, longitude: 2.4080, priority: 10, isServiceable: true },
  { id: "bj-sikecodji", name: "Sikècodji", normalizedName: "sikecodji", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["sike codji", "sikecodji cotonou"], latitude: 6.3900, longitude: 2.4150, priority: 10, isServiceable: true },
  { id: "bj-sainterita", name: "Sainte Rita", normalizedName: "sainte rita", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["ste rita", "sainte-rita"], latitude: 6.3480, longitude: 2.4020, priority: 10, isServiceable: true },
  { id: "bj-menontin", name: "Mènontin", normalizedName: "menontin", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["menontin cotonou", "menontin centre"], latitude: 6.3740, longitude: 2.4350, priority: 10, isServiceable: true },
  { id: "bj-agla", name: "Agla", normalizedName: "agla", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["agla cotonou"], latitude: 6.3780, longitude: 2.4400, priority: 10, isServiceable: true },
  { id: "bj-vedoko", name: "Vèdoko", normalizedName: "vedoko", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["vedoko", "vedoko cotonou"], latitude: 6.3820, longitude: 2.4450, priority: 10, isServiceable: true },
  { id: "bj-jericho", name: "Jéricho", normalizedName: "jericho", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["jericho cotonou"], latitude: 6.3450, longitude: 2.3950, priority: 10, isServiceable: true },
  { id: "bj-kouhounou", name: "Kouhounou", normalizedName: "kouhounou", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["kouhounou cotonou"], latitude: 6.3400, longitude: 2.4050, priority: 10, isServiceable: true },
  { id: "bj-vodje", name: "Vodjè", normalizedName: "vodje", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["vodje", "vodje cotonou"], latitude: 6.3550, longitude: 2.4100, priority: 10, isServiceable: true },
  { id: "bj-pattedoie", name: "Patte d'Oie", normalizedName: "patte doie", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["patte d oie", "patte-doie"], latitude: 6.3500, longitude: 2.4150, priority: 10, isServiceable: true },
  { id: "bj-fifadji", name: "Fifadji", normalizedName: "fifadji", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["fifadji cotonou"], latitude: 6.3420, longitude: 2.4180, priority: 10, isServiceable: true },
  { id: "bj-missebo", name: "Missèbo", normalizedName: "missebo", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["missebo cotonou"], latitude: 6.3480, longitude: 2.4220, priority: 10, isServiceable: true },
  { id: "bj-jonquet", name: "Jonquet", normalizedName: "jonquet", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["jonquet cotonou"], latitude: 6.3650, longitude: 2.4050, priority: 10, isServiceable: true },
  { id: "bj-placodji", name: "Placodji", normalizedName: "placodji", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["placodji cotonou"], latitude: 6.3720, longitude: 2.3950, priority: 10, isServiceable: true },
  { id: "bj-xwlacodji", name: "Xwlacodji", normalizedName: "xwlacodji", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["xwlacodji cotonou"], latitude: 6.3750, longitude: 2.3980, priority: 10, isServiceable: true },
  { id: "bj-enagnon", name: "Enagnon", normalizedName: "enagnon", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["enagnon cotonou"], latitude: 6.3800, longitude: 2.4000, priority: 10, isServiceable: true },
  { id: "bj-aidjedo", name: "Aidjedo", normalizedName: "aidjedo", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["aidjedo cotonou"], latitude: 6.3850, longitude: 2.4050, priority: 10, isServiceable: true },
  { id: "bj-aibatin", name: "Aibatin", normalizedName: "aibatin", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["aibatin cotonou"], latitude: 6.3900, longitude: 2.4100, priority: 10, isServiceable: true },
  { id: "bj-kindonou", name: "Kindonou", normalizedName: "kindonou", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["kindonou cotonou"], latitude: 6.3950, longitude: 2.4150, priority: 10, isServiceable: true },
  { id: "bj-houenoussou", name: "Houénoussou", normalizedName: "houenoussou", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["houenoussou cotonou"], latitude: 6.4000, longitude: 2.4200, priority: 10, isServiceable: true },
  { id: "bj-ahouansori", name: "Ahouansori", normalizedName: "ahouansori", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["ahouansori cotonou"], latitude: 6.4050, longitude: 2.4250, priority: 10, isServiceable: true },
  { id: "bj-ladji", name: "Ladji", normalizedName: "ladji", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["ladji cotonou"], latitude: 6.4100, longitude: 2.4300, priority: 10, isServiceable: true },
  { id: "bj-djidje", name: "Djidjè", normalizedName: "djidje", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["djidje cotonou"], latitude: 6.4150, longitude: 2.4350, priority: 10, isServiceable: true },
  { id: "bj-avotrou", name: "Avotrou", normalizedName: "avotrou", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["avotrou cotonou"], latitude: 6.4200, longitude: 2.4400, priority: 10, isServiceable: true },
  { id: "bj-yenawa", name: "Yénawa", normalizedName: "yenawa", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["yenawa cotonou"], latitude: 6.4250, longitude: 2.4450, priority: 10, isServiceable: true },
  { id: "bj-agontinkon", name: "Agontinkon", normalizedName: "agontinkon", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["agontinkon cotonou"], latitude: 6.4300, longitude: 2.4500, priority: 10, isServiceable: true },
  { id: "bj-wologuede", name: "Wologuèdè", normalizedName: "wologuede", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["wologuede cotonou"], latitude: 6.4350, longitude: 2.4550, priority: 10, isServiceable: true },
  { id: "bj-hinde", name: "Hindé", normalizedName: "hinde", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["hinde cotonou"], latitude: 6.4400, longitude: 2.4600, priority: 10, isServiceable: true },
  { id: "bj-saintmichel", name: "Saint Michel", normalizedName: "saint michel", type: "QUARTIER", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["st michel", "saint-michel"], latitude: 6.4450, longitude: 2.4650, priority: 10, isServiceable: true },
  { id: "bj-campguezo", name: "Camp Guézo", normalizedName: "camp guezo", type: "LANDMARK", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["camp guezo", "guézo"], latitude: 6.3500, longitude: 2.3800, priority: 10, isServiceable: true },
  { id: "bj-etoilerouge", name: "Étoile Rouge", normalizedName: "etoile rouge", type: "LANDMARK", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["etoile rouge", "étoile-rouge"], latitude: 6.3600, longitude: 2.3900, priority: 10, isServiceable: true },
  { id: "bj-carrefourtoyota", name: "Carrefour Toyota", normalizedName: "carrefour toyota", type: "LANDMARK", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["toyota cotonou", "carrefour toyota"], latitude: 6.3650, longitude: 2.3950, priority: 10, isServiceable: true },
  { id: "bj-stadeamitie", name: "Stade de l'Amitié", normalizedName: "stade de lamitie", type: "LANDMARK", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["stade amitie", "stade de l amitie"], latitude: 6.3700, longitude: 2.4000, priority: 10, isServiceable: true },
  { id: "bj-aeroport-cotonou", name: "Aéroport de Cotonou", normalizedName: "aeroport de cotonou", type: "LANDMARK", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["aeroport cadjehoun", "cadjehoun aeroport"], latitude: 6.3572, longitude: 2.3844, priority: 10, isServiceable: true },
  { id: "bj-boulevard-steinmetz", name: "Boulevard Steinmetz", normalizedName: "boulevard steinmetz", type: "LANDMARK", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["steinmetz", "bvd steinmetz"], latitude: 6.3650, longitude: 2.4100, priority: 10, isServiceable: true },
  { id: "bj-marina", name: "Marina", normalizedName: "marina", type: "LANDMARK", department: "Littoral", commune: "Cotonou", arrondissement: null, city: "Cotonou", country: "Bénin", aliases: ["marina cotonou"], latitude: 6.3550, longitude: 2.3850, priority: 10, isServiceable: true },

  // ===================== ABOMEY-CALAVI (Atlantique) =====================
  { id: "bj-abomey-calavi", name: "Abomey-Calavi", normalizedName: "abomey calavi", type: "COMMUNE", department: "Atlantique", commune: "Abomey-Calavi", arrondissement: null, city: "Abomey-Calavi", country: "Bénin", aliases: ["calavi", "abomey calavi ville"], latitude: 6.4489, longitude: 2.3406, priority: 10, isServiceable: true },
  { id: "bj-calavi", name: "Calavi", normalizedName: "calavi", type: "QUARTIER", department: "Atlantique", commune: "Abomey-Calavi", arrondissement: null, city: "Abomey-Calavi", country: "Bénin", aliases: ["calavi centre"], latitude: 6.4500, longitude: 2.3450, priority: 10, isServiceable: true },
  { id: "bj-godomey", name: "Godomey", normalizedName: "godomey", type: "QUARTIER", department: "Atlantique", commune: "Abomey-Calavi", arrondissement: null, city: "Abomey-Calavi", country: "Bénin", aliases: ["godomey calavi"], latitude: 6.4600, longitude: 2.3500, priority: 10, isServiceable: true },
  { id: "bj-cocotomey", name: "Cocotomey", normalizedName: "cocotomey", type: "QUARTIER", department: "Atlantique", commune: "Abomey-Calavi", arrondissement: null, city: "Abomey-Calavi", country: "Bénin", aliases: ["cocotomey calavi"], latitude: 6.4700, longitude: 2.3550, priority: 10, isServiceable: true },
  { id: "bj-togoudo", name: "Togoudo", normalizedName: "togoudo", type: "QUARTIER", department: "Atlantique", commune: "Abomey-Calavi", arrondissement: null, city: "Abomey-Calavi", country: "Bénin", aliases: ["togoudo calavi"], latitude: 6.4800, longitude: 2.3600, priority: 10, isServiceable: true },
  { id: "bj-zogbadje", name: "Zogbadjè", normalizedName: "zogbadje", type: "QUARTIER", department: "Atlantique", commune: "Abomey-Calavi", arrondissement: null, city: "Abomey-Calavi", country: "Bénin", aliases: ["zogbadje calavi"], latitude: 6.4900, longitude: 2.3650, priority: 10, isServiceable: true },
  { id: "bj-akassato", name: "Akassato", normalizedName: "akassato", type: "QUARTIER", department: "Atlantique", commune: "Abomey-Calavi", arrondissement: null, city: "Abomey-Calavi", country: "Bénin", aliases: ["akassato calavi"], latitude: 6.5000, longitude: 2.3700, priority: 10, isServiceable: true },
  { id: "bj-glo-djigbe", name: "Glo-Djigbé", normalizedName: "glo djigbe", type: "QUARTIER", department: "Atlantique", commune: "Abomey-Calavi", arrondissement: null, city: "Abomey-Calavi", country: "Bénin", aliases: ["glo djigbe", "glodjigbe"], latitude: 6.5100, longitude: 2.3750, priority: 10, isServiceable: true },
  { id: "bj-hevie", name: "Hêvié", normalizedName: "hevie", type: "QUARTIER", department: "Atlantique", commune: "Abomey-Calavi", arrondissement: null, city: "Abomey-Calavi", country: "Bénin", aliases: ["hevie calavi"], latitude: 6.5200, longitude: 2.3800, priority: 10, isServiceable: true },
  { id: "bj-ouedo", name: "Ouèdo", normalizedName: "ouedo", type: "QUARTIER", department: "Atlantique", commune: "Abomey-Calavi", arrondissement: null, city: "Abomey-Calavi", country: "Bénin", aliases: ["ouedo calavi"], latitude: 6.5300, longitude: 2.3850, priority: 10, isServiceable: true },
  { id: "bj-tankpe", name: "Tankpè", normalizedName: "tankpe", type: "QUARTIER", department: "Atlantique", commune: "Abomey-Calavi", arrondissement: null, city: "Abomey-Calavi", country: "Bénin", aliases: ["tankpe calavi"], latitude: 6.5400, longitude: 2.3900, priority: 10, isServiceable: true },
  { id: "bj-arconville", name: "Arconville", normalizedName: "arconville", type: "QUARTIER", department: "Atlantique", commune: "Abomey-Calavi", arrondissement: null, city: "Abomey-Calavi", country: "Bénin", aliases: ["arconville calavi"], latitude: 6.5500, longitude: 2.3950, priority: 10, isServiceable: true },
  { id: "bj-bidossessi", name: "Bidossessi", normalizedName: "bidossessi", type: "QUARTIER", department: "Atlantique", commune: "Abomey-Calavi", arrondissement: null, city: "Abomey-Calavi", country: "Bénin", aliases: ["bidossessi calavi"], latitude: 6.5600, longitude: 2.4000, priority: 10, isServiceable: true },
  { id: "bj-aitchedji", name: "Aïtchédji", normalizedName: "aitchedji", type: "QUARTIER", department: "Atlantique", commune: "Abomey-Calavi", arrondissement: null, city: "Abomey-Calavi", country: "Bénin", aliases: ["aitchedji calavi"], latitude: 6.5700, longitude: 2.4050, priority: 10, isServiceable: true },
  { id: "bj-zinvie", name: "Zinvié", normalizedName: "zinvie", type: "QUARTIER", department: "Atlantique", commune: "Abomey-Calavi", arrondissement: null, city: "Abomey-Calavi", country: "Bénin", aliases: ["zinvie calavi"], latitude: 6.5800, longitude: 2.4100, priority: 10, isServiceable: true },
  { id: "bj-kpanroun", name: "Kpanroun", normalizedName: "kpanroun", type: "QUARTIER", department: "Atlantique", commune: "Abomey-Calavi", arrondissement: null, city: "Abomey-Calavi", country: "Bénin", aliases: ["kpanroun calavi"], latitude: 6.5900, longitude: 2.4150, priority: 10, isServiceable: true },

  // ===================== SÈMÈ-KPODJI (Ouémé) =====================
  { id: "bj-seme-kpodji", name: "Sèmè-Kpodji", normalizedName: "seme kpodji", type: "COMMUNE", department: "Ouémé", commune: "Sèmè-Kpodji", arrondissement: null, city: "Sèmè-Kpodji", country: "Bénin", aliases: ["seme kpodji ville"], latitude: 6.3720, longitude: 2.5500, priority: 10, isServiceable: true },
  { id: "bj-ekpe", name: "Ekpè", normalizedName: "ekpe", type: "QUARTIER", department: "Ouémé", commune: "Sèmè-Kpodji", arrondissement: null, city: "Sèmè-Kpodji", country: "Bénin", aliases: ["ekpe seme"], latitude: 6.3800, longitude: 2.5600, priority: 10, isServiceable: true },
  { id: "bj-agblangandan", name: "Agblangandan", normalizedName: "agblangandan", type: "QUARTIER", department: "Ouémé", commune: "Sèmè-Kpodji", arrondissement: null, city: "Sèmè-Kpodji", country: "Bénin", aliases: ["agblangandan seme"], latitude: 6.3900, longitude: 2.5700, priority: 10, isServiceable: true },
  { id: "bj-seme", name: "Sèmè", normalizedName: "seme", type: "QUARTIER", department: "Ouémé", commune: "Sèmè-Kpodji", arrondissement: null, city: "Sèmè-Kpodji", country: "Bénin", aliases: ["seme centre"], latitude: 6.4000, longitude: 2.5800, priority: 10, isServiceable: true },
  { id: "bj-krake", name: "Kraké", normalizedName: "krake", type: "QUARTIER", department: "Ouémé", commune: "Sèmè-Kpodji", arrondissement: null, city: "Sèmè-Kpodji", country: "Bénin", aliases: ["krake seme"], latitude: 6.4100, longitude: 2.5900, priority: 10, isServiceable: true },
  { id: "bj-tohoue", name: "Tohouè", normalizedName: "tohoue", type: "QUARTIER", department: "Ouémé", commune: "Sèmè-Kpodji", arrondissement: null, city: "Sèmè-Kpodji", country: "Bénin", aliases: ["tohoue seme"], latitude: 6.4200, longitude: 2.6000, priority: 10, isServiceable: true },
  { id: "bj-djregbe", name: "Djrègbé", normalizedName: "djregbe", type: "QUARTIER", department: "Ouémé", commune: "Sèmè-Kpodji", arrondissement: null, city: "Sèmè-Kpodji", country: "Bénin", aliases: ["djregbe seme"], latitude: 6.4300, longitude: 2.6100, priority: 10, isServiceable: true },

  // ===================== PORTO-NOVO (Ouémé) =====================
  { id: "bj-porto-novo", name: "Porto-Novo", normalizedName: "porto novo", type: "COMMUNE", department: "Ouémé", commune: "Porto-Novo", arrondissement: null, city: "Porto-Novo", country: "Bénin", aliases: ["portonovo", "porto novo ville"], latitude: 6.4969, longitude: 2.6283, priority: 9, isServiceable: true },
  { id: "bj-ouando", name: "Ouando", normalizedName: "ouando", type: "QUARTIER", department: "Ouémé", commune: "Porto-Novo", arrondissement: null, city: "Porto-Novo", country: "Bénin", aliases: ["ouando porto novo"], latitude: 6.5050, longitude: 2.6350, priority: 9, isServiceable: true },
  { id: "bj-djassin", name: "Djassin", normalizedName: "djassin", type: "QUARTIER", department: "Ouémé", commune: "Porto-Novo", arrondissement: null, city: "Porto-Novo", country: "Bénin", aliases: ["djassin porto novo"], latitude: 6.5100, longitude: 2.6400, priority: 9, isServiceable: true },
  { id: "bj-tokpota", name: "Tokpota", normalizedName: "tokpota", type: "QUARTIER", department: "Ouémé", commune: "Porto-Novo", arrondissement: null, city: "Porto-Novo", country: "Bénin", aliases: ["tokpota porto novo"], latitude: 6.5150, longitude: 2.6450, priority: 9, isServiceable: true },
  { id: "bj-kandevie", name: "Kandévié", normalizedName: "kandevie", type: "QUARTIER", department: "Ouémé", commune: "Porto-Novo", arrondissement: null, city: "Porto-Novo", country: "Bénin", aliases: ["kandevie porto novo"], latitude: 6.5200, longitude: 2.6500, priority: 9, isServiceable: true },
  { id: "bj-hounsa", name: "Hounsa", normalizedName: "hounsa", type: "QUARTIER", department: "Ouémé", commune: "Porto-Novo", arrondissement: null, city: "Porto-Novo", country: "Bénin", aliases: ["hounsa porto novo"], latitude: 6.5250, longitude: 2.6550, priority: 9, isServiceable: true },
  { id: "bj-adjara", name: "Adjara", normalizedName: "adjara", type: "QUARTIER", department: "Ouémé", commune: "Porto-Novo", arrondissement: null, city: "Porto-Novo", country: "Bénin", aliases: ["adjara porto novo"], latitude: 6.5300, longitude: 2.6600, priority: 9, isServiceable: true },
  { id: "bj-avrankou", name: "Avrankou", normalizedName: "avrankou", type: "COMMUNE", department: "Ouémé", commune: "Avrankou", arrondissement: null, city: "Avrankou", country: "Bénin", aliases: ["avrankou oueme"], latitude: 6.5500, longitude: 2.6700, priority: 8, isServiceable: true },

  // ===================== AUTRES VILLES =====================
  { id: "bj-parakou", name: "Parakou", normalizedName: "parakou", type: "COMMUNE", department: "Borgou", commune: "Parakou", arrondissement: null, city: "Parakou", country: "Bénin", aliases: ["parakou ville"], latitude: 9.3371, longitude: 2.6307, priority: 7, isServiceable: false },
  { id: "bj-abomey", name: "Abomey", normalizedName: "abomey", type: "COMMUNE", department: "Zou", commune: "Abomey", arrondissement: null, city: "Abomey", country: "Bénin", aliases: ["abomey ville"], latitude: 7.1829, longitude: 1.9886, priority: 7, isServiceable: false },
  { id: "bj-bohicon", name: "Bohicon", normalizedName: "bohicon", type: "COMMUNE", department: "Zou", commune: "Bohicon", arrondissement: null, city: "Bohicon", country: "Bénin", aliases: ["bohicon ville"], latitude: 7.1783, longitude: 2.0667, priority: 7, isServiceable: false },
  { id: "bj-ouidah", name: "Ouidah", normalizedName: "ouidah", type: "COMMUNE", department: "Atlantique", commune: "Ouidah", arrondissement: null, city: "Ouidah", country: "Bénin", aliases: ["ouidah ville", "whydah"], latitude: 6.3667, longitude: 2.0833, priority: 7, isServiceable: false },
  { id: "bj-natitingou", name: "Natitingou", normalizedName: "natitingou", type: "COMMUNE", department: "Atakora", commune: "Natitingou", arrondissement: null, city: "Natitingou", country: "Bénin", aliases: ["natitingou ville"], latitude: 10.3042, longitude: 1.3796, priority: 7, isServiceable: false },
  { id: "bj-djougou", name: "Djougou", normalizedName: "djougou", type: "COMMUNE", department: "Donga", commune: "Djougou", arrondissement: null, city: "Djougou", country: "Bénin", aliases: ["djougou ville"], latitude: 9.7085, longitude: 1.6650, priority: 7, isServiceable: false },
  { id: "bj-lokossa", name: "Lokossa", normalizedName: "lokossa", type: "COMMUNE", department: "Mono", commune: "Lokossa", arrondissement: null, city: "Lokossa", country: "Bénin", aliases: ["lokossa ville"], latitude: 6.3667, longitude: 1.7167, priority: 7, isServiceable: false },
  { id: "bj-aplahoue", name: "Aplahoué", normalizedName: "aplahoue", type: "COMMUNE", department: "Mono", commune: "Aplahoué", arrondissement: null, city: "Aplahoué", country: "Bénin", aliases: ["aplahoue ville"], latitude: 6.9333, longitude: 1.6833, priority: 7, isServiceable: false },
  { id: "bj-pobe", name: "Pobè", normalizedName: "pobe", type: "COMMUNE", department: "Plateau", commune: "Pobè", arrondissement: null, city: "Pobè", country: "Bénin", aliases: ["pobe ville"], latitude: 6.9800, longitude: 2.6650, priority: 7, isServiceable: false },
  { id: "bj-ketou", name: "Kétou", normalizedName: "ketou", type: "COMMUNE", department: "Plateau", commune: "Kétou", arrondissement: null, city: "Kétou", country: "Bénin", aliases: ["ketou ville"], latitude: 7.3633, longitude: 2.6083, priority: 7, isServiceable: false },
  { id: "bj-save", name: "Savè", normalizedName: "save", type: "COMMUNE", department: "Collines", commune: "Savè", arrondissement: null, city: "Savè", country: "Bénin", aliases: ["save ville"], latitude: 7.9897, longitude: 2.5100, priority: 7, isServiceable: false },
  { id: "bj-savalou", name: "Savalou", normalizedName: "savalou", type: "COMMUNE", department: "Collines", commune: "Savalou", arrondissement: null, city: "Savalou", country: "Bénin", aliases: ["savalou ville"], latitude: 7.9500, longitude: 1.7833, priority: 7, isServiceable: false },
  { id: "bj-malanville", name: "Malanville", normalizedName: "malanville", type: "COMMUNE", department: "Alibori", commune: "Malanville", arrondissement: null, city: "Malanville", country: "Bénin", aliases: ["malanville ville"], latitude: 11.8667, longitude: 3.3833, priority: 7, isServiceable: false },
  { id: "bj-kandi", name: "Kandi", normalizedName: "kandi", type: "COMMUNE", department: "Alibori", commune: "Kandi", arrondissement: null, city: "Kandi", country: "Bénin", aliases: ["kandi ville"], latitude: 11.4167, longitude: 2.9333, priority: 7, isServiceable: false },
  { id: "bj-nikki", name: "Nikki", normalizedName: "nikki", type: "COMMUNE", department: "Borgou", commune: "Nikki", arrondissement: null, city: "Nikki", country: "Bénin", aliases: ["nikki ville"], latitude: 9.9400, longitude: 3.2100, priority: 7, isServiceable: false },
  { id: "bj-banikoara", name: "Banikoara", normalizedName: "banikoara", type: "COMMUNE", department: "Alibori", commune: "Banikoara", arrondissement: null, city: "Banikoara", country: "Bénin", aliases: ["banikoara ville"], latitude: 11.3000, longitude: 2.4333, priority: 7, isServiceable: false },
  { id: "bj-cove", name: "Covè", normalizedName: "cove", type: "COMMUNE", department: "Zou", commune: "Covè", arrondissement: null, city: "Covè", country: "Bénin", aliases: ["cove ville"], latitude: 7.2200, longitude: 2.3400, priority: 7, isServiceable: false },
  { id: "bj-allada", name: "Allada", normalizedName: "allada", type: "COMMUNE", department: "Atlantique", commune: "Allada", arrondissement: null, city: "Allada", country: "Bénin", aliases: ["allada ville"], latitude: 6.6667, longitude: 2.1500, priority: 7, isServiceable: false },
  { id: "bj-come", name: "Comè", normalizedName: "come", type: "COMMUNE", department: "Mono", commune: "Comè", arrondissement: null, city: "Comè", country: "Bénin", aliases: ["come ville"], latitude: 6.4000, longitude: 1.8833, priority: 7, isServiceable: false },
  { id: "bj-grand-popo", name: "Grand-Popo", normalizedName: "grand popo", type: "COMMUNE", department: "Mono", commune: "Grand-Popo", arrondissement: null, city: "Grand-Popo", country: "Bénin", aliases: ["grand popo ville"], latitude: 6.2833, longitude: 1.8333, priority: 7, isServiceable: false },
  { id: "bj-sakete", name: "Sakété", normalizedName: "sakete", type: "COMMUNE", department: "Plateau", commune: "Sakété", arrondissement: null, city: "Sakété", country: "Bénin", aliases: ["sakete ville"], latitude: 6.7333, longitude: 2.6500, priority: 7, isServiceable: false },
  { id: "bj-tchaourou", name: "Tchaourou", normalizedName: "tchaourou", type: "COMMUNE", department: "Borgou", commune: "Tchaourou", arrondissement: null, city: "Tchaourou", country: "Bénin", aliases: ["tchaourou ville"], latitude: 8.8833, longitude: 2.6000, priority: 7, isServiceable: false },
  { id: "bj-bassila", name: "Bassila", normalizedName: "bassila", type: "COMMUNE", department: "Donga", commune: "Bassila", arrondissement: null, city: "Bassila", country: "Bénin", aliases: ["bassila ville"], latitude: 9.0000, longitude: 1.6667, priority: 7, isServiceable: false },
  { id: "bj-tangueta", name: "Tanguiéta", normalizedName: "tangueta", type: "COMMUNE", department: "Atakora", commune: "Tanguiéta", arrondissement: null, city: "Tanguiéta", country: "Bénin", aliases: ["tangueta ville"], latitude: 10.6167, longitude: 1.2667, priority: 7, isServiceable: false },
];
